Add item durability
CFC-Servers/raft_v_raft pull request #30
Opened 2020-07-13 00:33 UTC by samuelWilliams99

An item can define `hasDurability`, `durabilityUse`, `maxDurability` and `durabilityUseRandomRange`.
Adds a durability bar on item slots
Defines a `LoseDurability()` function on the weapon when it is spawned if the item it is assigned to has durability.
The SWEP is expected to call this whenever used in some way that would damage it.

2020-07-13 18:49 UTC, ghost requested changes

2020-07-13 18:49 UTC, Periapsises commented on gamemode/modules/inventory/sv_inventory.lua
> +    function wep:LoseDurability()
Is this function unused? It's not returned nor called so unless there is something about lua that I never knew about I feel like there is a problem here.

2020-07-13 18:51 UTC, Periapsises commented on gamemode/modules/inventory/sv_inventory.lua
> +    function wep:LoseDurability()
Nvm my bad this is fine

2020-07-13 18:51 UTC, ghost approved these changes
Looks good to me

2020-07-17 17:19 UTC, overlordbleck approved these changes
hot

2020-07-19 16:33 UTC, merged