Raft health + repair
CFC-Servers/raft_v_raft pull request #44
Opened 2020-07-24 23:48 UTC by samuelWilliams99

Adds ability to damage + destroy raft pieces
Adds tape item, which heals raft parts in exchange for durability

![image](https://user-images.githubusercontent.com/33094920/88443532-97373e00-ce10-11ea-876d-c6e8c24c488a.png)

TODO:
- [ ] Tape model
- [ ] Handle orphan raft parts

2020-07-28 15:46 UTC, plally requested changes

2020-07-28 15:46 UTC, plally commented on entities/weapons/rvr_repair_tool/cl_init.lua
> +function SWEP:GetHudIdentifier()
a  better name would be `GetHookIdentifier`. it is used for halos as well

2020-07-28 15:46 UTC, plally commented on gamemode/modules/rafts/sh_raft_class.lua
> +        if not IsValid( raftPiece ) then continue end
perhaps you could put alot of this in a local function then the loop would become something like  
```lua
for _, raftPiece in pairs( self.pieces ) do
    if IsValid( raftPiece ) then
        local pos = getValidSpawnPos( ply, raftPiece )
        if pos then return pos end

        if raftPiece:GetPos().z > highestPiece:GetPos().z then
            highestPiece = raftPiece
        end
    end
end
```
(im not saying I require this, if you like the continue thats fine)

2020-07-28 19:52 UTC, plally commented on gamemode/modules/rafts/sh_raft_class.lua
> +    if config.SPAWNPOINT_PARTS[raftPiece:GetClass()] then
return early

2020-07-29 18:24 UTC, overlordbleck reviewed
Better than PCL's

2020-07-29 18:24 UTC, overlordbleck commented on gamemode/modules/rafts/sh_raft_class.lua
> +    local segments = RVR.Util.segmentGrid( grid )
```suggestion
    if piece:GetClass() ~= "raft_foundation" then return end
    if piece.removedByRaft then return end

    local grid, piecesGrid = self:GetSegmentingGrid()
    local segments = RVR.Util.segmentGrid( grid )
```

2020-07-29 22:31 UTC, merged