Feature/party invite popup
CFC-Servers/raft_v_raft pull request #49
Opened 2020-07-26 23:46 UTC by samuelWilliams99

![image](https://user-images.githubusercontent.com/33094920/88492413-9504e900-cfa2-11ea-82d3-52f90deff45c.png)

Also adds F3 to toggle mouse input and fixes a bug with players joining after parties created

2020-07-28 03:35 UTC, plally requested changes

2020-07-28 03:35 UTC, plally commented on gamemode/modules/party/sv_party.lua
> +    net.WriteTable( party.parties )
werent we indenting net messages?

2020-07-28 14:36 UTC, plally commented on gamemode/modules/party/cl_party.lua
> +end )
```lua
hook.Add( "PlayerBindPress", "", function( ply, bind, pressed )
    if not ( pressed and bind == "gm_showspare1" ) then return end
    -- stuff
end )
```

2020-07-29 13:03 UTC, plally approved these changes

2020-07-29 17:49 UTC, overlordbleck approved these changes
🎈

2020-07-29 17:49 UTC, overlordbleck commented on gamemode/modules/party/cl_party_invite_popup.lua
> +local function makeButton( text, x, y, h, frame, f )
f > func

2020-07-29 17:49 UTC, overlordbleck commented on gamemode/modules/party/cl_party_invite_popup.lua
> +end
balloon pop

2020-07-29 17:49 UTC, overlordbleck commented on gamemode/modules/party/sv_party.lua
> +
```suggestion
```

personal preference, I like to keep my variables in one spot

2020-07-29 18:04 UTC, samuelWilliams99 commented on gamemode/modules/party/cl_party_invite_popup.lua
> +local function makeButton( text, x, y, h, frame, f )
I agree, f is better than func

2020-07-29 20:50 UTC, merged